import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, test } from 'vitest';

const here = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(here, 'useNativeIosComposer.ts'), 'utf-8');

describe('useNativeIosComposer', () => {
  test('keeps send, attach, model, and agent as ChatInput events and uses useEvent', () => {
    expect(source).toContain("from '@reactuses/core'");
    expect(source).toContain('useEvent');
    expect(source).not.toContain('useCallback');
    expect(source).toContain('onSend');
    expect(source).toContain('onAttach');
    expect(source).toContain('onFiles');
    expect(source).toContain('onRemoveAttachment');
    expect(source).toContain('attachmentPreviews');
    expect(source).toContain('citationRanges');
    expect(source).toContain('chipRanges');
    expect(source).toContain('chipHighlights');
    expect(source).toContain('buildNativeComposerChipRanges');
    expect(source).toContain("resolveCssVarToHex('--primary')");
    expect(source).not.toContain('NATIVE_IOS_COMPOSER_CHIPS_ENABLED');
    expect(source).not.toContain('nativeChipIconCache');
    expect(source).not.toContain('chipIconKey');
    expect(source).not.toContain('[available, chipIconKey, args.text]');
    expect(source).toContain('rasterizeAttachmentThumbnailBase64');
    expect(source).toContain('findAttachmentCitationRanges');
    expect(source).toContain('resolveModelLogoSrc');
    expect(source).toContain('rasterizeLogoPngBase64');
    expect(source).toContain('republish name + thinking');
    expect(source).toContain('modelLabel: args.modelLabel');
    expect(source).toContain('modelVariantLabel: args.modelVariantLabel');
    expect(source).toContain('onOpenModel');
    expect(source).toContain('onCycleAgent');
    expect(source).toContain('onOpenAgent');
    expect(source).toContain('onScrollToBottom');
    expect(source).toContain('showScrollToBottom: args.showScrollToBottom');
    expect(source).toContain('resolveNativeComposerTextWrite');
    expect(source).toContain('shouldIgnoreNativeComposerTextEcho');
    expect(source).toContain('textPresetEpoch');
    expect(source).toContain('preset');
    expect(source).toContain('buildNativeComposerUpdatePayload');
    expect(source).toContain('echoingNativeRef');
    expect(source).toContain('echoingNativeRef.current = true');
    expect(source).toContain(`onSend: (text) => {
      nativeTextRef.current = text;
      onSend(text);
    }`);
    expect(source).not.toContain(`onSend: (text) => {
      nativeTextRef.current = text;
      echoingNativeRef.current = true;`);
    expect(source).toContain('useLayoutEffect');
    expect(source).toContain('setNativeComposerDocumentClass(root, true)');
    expect(source).toContain('nativeIosComposerSession.retain');
    expect(source).toContain('nativeIosComposerSession.release');
    expect(source).toContain('nativeIosComposerSession.bind');
    expect(source).toContain('nativeIosComposerSession.rememberState');
    expect(source).toContain('attachNativeIosComposerLeaveConceal');
    expect(source).toContain('nativeIosComposerSession.rememberState');
    expect(source).toContain('getNativeIosComposerPlugin().update');
    expect(source).toContain('applyNativeComposerHeightVar');
    expect(source).toContain('packNativeIosComposerIdenticon');
    const chatInput = readFileSync(join(here, 'ChatInput.tsx'), 'utf-8');
    expect(chatInput).toContain('handoffNativeComposerSendToWeb');
    expect(chatInput).toContain('submit: handlePrimaryAction');
    expect(chatInput).toContain('useSessionMaterializationStatus');
    expect(chatInput).toContain('transcriptReady: primaryTranscriptRenderable');
    expect(chatInput).toContain('shouldHoldPrimaryComposerUserPick');
    expect(chatInput).toContain('primarySelectionPinnedHistoryIdRef');
    expect(chatInput).not.toContain('applyProgrammaticEdit(text);\n            handlePrimaryAction();');
    expect(source).toContain('modelVariantLabel');
    expect(source).toContain('queueAria');
    expect(source).toContain('attachPhotosLabel');
    expect(source).toContain('attachFilesLabel');
    expect(source).toContain('attachCancelLabel');
    expect(source).toContain('autocompleteRows');
    expect(source).toContain('onAutocompleteAccept');
    expect(source).toContain('echoingNativeRef.current = false');
    expect(source).toContain('caret: args.caret');
    expect(source).toContain('rasterizeSpriteIconPngBase64');
    expect(chatInput).toContain('resolveComposerAutocompleteReplaceRange');
    expect(chatInput).toContain('autocompleteTriggerRef');
    expect(chatInput).toContain('caret: cursorPosRef.current');
    expect(chatInput).toContain('chipHighlights: highlightedComposerContent');
    expect(chatInput).toContain('nativeComposerOwnedInput');
    expect(chatInput).toContain('textPresetEpoch: composer.textPresetEpoch');
    expect(chatInput).toContain('getNativeIosComposerPlugin().focus()');
    expect(chatInput).toContain('nativeComposerOwnedInput ? [] : tokenizeMarkdown(message)');
    expect(chatInput).toContain('nativeComposerOwnedInput ? [] : highlightFencedCode(message)');
  });
});
