apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'com.yee94.openchamber.shell'
version = '1.19.7-beta.7'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
if (expoModulesCorePlugin.exists()) {
  apply from: expoModulesCorePlugin
  applyKotlinExpoModulesCorePlugin()
  useDefaultAndroidSdkVersions()
} else {
  android {
    namespace "com.yee94.openchamber.shell"
    compileSdkVersion safeExtGet("compileSdkVersion", 35)
    defaultConfig {
      minSdkVersion safeExtGet("minSdkVersion", 24)
      targetSdkVersion safeExtGet("targetSdkVersion", 35)
    }
  }
}

dependencies {
  implementation project(':expo-modules-core')
}
